version: "3.7"

services:
  app:
    container_name: app
    build:
      context: ./app
    tty: true
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/.dockervenv:/src/.venv
      - ./app:/src
    ports:
      - 9200:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: db
    # restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5532:5432
